### ISSUE TITLE
内存访问越界

### ISSUE THREAD

**Issue by cnscns** [gityf/img-video#1]
0x00007ffff5dd106f in ?? ()
(gdb) bt
#0  0x00007ffff5dd106f in ?? ()
#1  0x000055555555d887 in X264Encoder::EncodeOneBuf (this=0x5555557b82e0, yuvMat=0x7fffffffe7b0, resStr=0x5555557bab88) at src/x264/x264_encoder.cpp:115
#2  0x000055555555dd4e in X264Encoder::EncodeOneFrame (this=0x5555557b82e0, frame=0x7fffffffe960, resStr=0x5555557bab88) at src/x264/x264_encoder.cpp:162
#3  0x000055555555e2c5 in StreamPush::push (this=0x5555557bab70, frame=0x7fffffffe960) at src/stream-push/StreamPush.cpp:41
#4  0x0000555555558a5d in handleVideo (pFileName=0x7fffffffed85 "./test.mp4") at src/main.cpp:46
#5  0x0000555555558b34 in main (argc=4, argv=0x7fffffffeb08) at src/main.cpp:54

**Comment by cnscns** [comment]
问题已经解决
